services:
  postgres:
    image: postgres:16-alpine
    container_name: first-step-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: first_step_local
    volumes:
      - first-step-postgres-data:/var/lib/postgresql/data

volumes:
  first-step-postgres-data:
